# Generated by Django 2.2.3 on 2019-07-22 05:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardDetail',
            fields=[
                ('created_time', models.DateTimeField(auto_created=True)),
                ('card_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user_id', models.CharField(default='', max_length=10)),
                ('updated_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('trans_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('card_id', models.UUIDField(default=uuid.uuid4)),
                ('trans_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('merchant', models.CharField(default='', max_length=64)),
                ('merchant_category', models.CharField(default='', max_length=5)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('trans_error', models.BooleanField(default=True)),
                ('trans_message', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='CardControlDetail',
            fields=[
                ('cc_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('category', models.TextField(blank=True, default='')),
                ('merchant', models.TextField(blank=True, default='')),
                ('max_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('min_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('parent_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardcontrol.CardDetail')),
            ],
        ),
    ]
