# Generated by Django 2.2.3 on 2019-07-22 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardcontrol', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardcontroldetail',
            name='balance',
        ),
    ]
